-- 
-- ALTER SESSION to use the default pluggable database context.
-- Oracle XE: 
--      The user will be created in the default `XEPDB1`  pluggable database.
-- Oracle Free: 
--      The user will be created in the default `FREEPDB1` pluggable database. 
--
SET SERVEROUTPUT ON;

-- Block 1: Print ASCII Art Banner
BEGIN
    DBMS_OUTPUT.PUT_LINE('██╗███╗░░██╗██╗████████╗░░░░██████╗░██████╗░██╗░░░░░');
    DBMS_OUTPUT.PUT_LINE('██║████╗░██║██║╚══██╔══╝░░░██╔════╝██╔═══██╗██║░░░░░');
    DBMS_OUTPUT.PUT_LINE('██║██╔██╗██║██║░░░██║░░░░░░╚█████╗░██║██╗██║██║░░░░░');
    DBMS_OUTPUT.PUT_LINE('██║██║╚████║██║░░░██║░░░░░░░╚═══██╗╚██████╔╝██║░░░░░');
    DBMS_OUTPUT.PUT_LINE('██║██║░╚███║██║░░░██║░░░██╗██████╔╝░╚═██╔═╝░███████╗');
    DBMS_OUTPUT.PUT_LINE('╚═╝╚═╝░░╚══╝╚═╝░░░╚═╝░░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝');
END;
/

-- Block 2: Detect Image and Print Message FIRST, then End the Block (Flushing the Output)
VARIABLE g_target_pdb VARCHAR2(30);

DECLARE
    v_edition VARCHAR2(4000); 
BEGIN
    SELECT banner_full INTO v_edition FROM v$version WHERE ROWNUM = 1;

    IF INSTR(LOWER(v_edition), 'xe') > 0 THEN
        DBMS_OUTPUT.PUT_LINE('[init.sql]: Detected Oracle XE Image. Selecting PDB: XEPDB1...');
        :g_target_pdb := 'XEPDB1';
    ELSIF INSTR(LOWER(v_edition), 'free') > 0 THEN
        DBMS_OUTPUT.PUT_LINE('[init.sql]: Detected Oracle Free Image. Selecting PDB: FREEPDB1...');
        :g_target_pdb := 'FREEPDB1';
    ELSE
        DBMS_OUTPUT.PUT_LINE('[init.sql]: Unrecognized database version. Defaulting to XEPDB1...');
        :g_target_pdb := 'XEPDB1';
    END IF;
END;
/

-- Block 3: Execute the Session Container Alteration (Safely after printing)
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET CONTAINER = ' || :g_target_pdb;
END;
/

-- Block 4: Re-enable Server Output inside the new PDB container environment
SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('[init.sql]: Container switch verified. Initializing schema customization...');
END;
/


-- 1. Create a custom application user profile
CREATE USER my_test_user IDENTIFIED BY my_secure_password;

-- 2. Grant necessary development permissions
GRANT CONNECT, RESOURCE, CREATE VIEW TO my_test_user;

-- 3. Set unlimited storage space allocation for the user on the default tablespace
ALTER USER my_test_user QUOTA UNLIMITED ON USERS;

-- 4. Create a sample table under the new user schema context
CREATE TABLE my_test_user.todo_list (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(100) NOT NULL,
    status      VARCHAR2(20) DEFAULT 'PENDING',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Insert initial seed sample records (12 total rows)
INSERT INTO my_test_user.todo_list (title) VALUES ('Fix the quantum interference device broken by Stuart Bloom');
INSERT INTO my_test_user.todo_list (title) VALUES ('Escape the repressive AI on the idyllic version of Earth');
INSERT INTO my_test_user.todo_list (title) VALUES ('Enlist a powerful wizard to help Bert find a sorcery gift');
INSERT INTO my_test_user.todo_list (title) VALUES ('Survive the post-apocalyptic Pasadena and avoid giant moths');
INSERT INTO my_test_user.todo_list (title) VALUES ('Barter canned vegetables and cat food for rare comic books');
INSERT INTO my_test_user.todo_list (title) VALUES ('Overthrow military dictator Barry Kripke in alternate reality');
INSERT INTO my_test_user.todo_list (title) VALUES ('Locate Denise after she mysteriously disappears in the multiverse');
INSERT INTO my_test_user.todo_list (title) VALUES ('Convince doctors in the mental institution that the multiverse is real');
INSERT INTO my_test_user.todo_list (title) VALUES ('Break out of the Matrix pods before reality resets again');
INSERT INTO my_test_user.todo_list (title) VALUES ('Undo the multiverse Armageddon accidentally unleashed by the gang');
INSERT INTO my_test_user.todo_list (title) VALUES ('Help Gary secure his new job working for UPS');
INSERT INTO my_test_user.todo_list (title) VALUES ('Find the original universe where Leonard and Sheldon live');

COMMIT;
