-- ALTER SESSION to use the default pluggable database context (XEPDB1)
ALTER SESSION SET CONTAINER = XEPDB1;

-- 1. Create a custom application user profile
CREATE USER my_test_user IDENTIFIED BY my_secure_password;

-- 2. Grant necessary development permissions
GRANT CONNECT, RESOURCE, CREATE VIEW TO my_test_user;

-- 3. Set unlimited storage space allocation for the user on the default tablespace
ALTER USER my_test_user QUOTA UNLIMITED ON USERS;

-- 4. Create a sample table under the new user schema context
CREATE TABLE my_test_user.todo_list (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(100) NOT NULL,
    status      VARCHAR2(20) DEFAULT 'PENDING',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Insert initial seed sample records (10 total rows)
INSERT INTO my_test_user.todo_list (title) VALUES ('Configure Oracle XE Container');
INSERT INTO my_test_user.todo_list (title) VALUES ('Verify init.sql Schema Loading');
INSERT INTO my_test_user.todo_list (title) VALUES ('Setup Zorin OS 18.1 Client Drivers');
INSERT INTO my_test_user.todo_list (title) VALUES ('Establish Windows 11 CLI Variables');
INSERT INTO my_test_user.todo_list (title) VALUES ('Test Pluggable Database Connectivity');
INSERT INTO my_test_user.todo_list (title) VALUES ('Validate User Schema Tablespace Quota');
INSERT INTO my_test_user.todo_list (title) VALUES ('Implement Application Data Layer');
INSERT INTO my_test_user.todo_list (title) VALUES ('Review Database Performance Metrics');
INSERT INTO my_test_user.todo_list (title) VALUES ('Automate Backup Routine Scripts');
INSERT INTO my_test_user.todo_list (title) VALUES ('Finalize System Deployment Documentation');

COMMIT;
